---
title: "Ebola_Visualizations"
author: "Stephanie Stacy"
date: "August 9, 2016"
output: html_document
---
```{r}
require(ape)
require(hash)
require(phytools)
require(ctv)
require(phylobase)
require(adephylo)
require(dplyr)
require(stringr)
require(ggplot2)
require(RColorBrewer)
```

Formatting the full ebola tree data and calculating node probabilities
```{r}
#Ebola Data

#With Jitter, Population size of 1
ebola <- read.nexus(file="EBOV_Conakry_subtree.tree")
set.seed(7)
ebola$edge.length <- jitter(ebola$edge.length)
popsize=1

#Full Ebola Tree
e <- subtrees(ebola)
ebola.pr <- matrix(NA, nrow=length(e), ncol = 3)
colnames(ebola.pr) <- c("Node.Pr", "N.Tips", "ZScore")

for(i in 1:length(e)){
  ebola.pr[i,1] <- nu.node.prob(ebola, e[[i]], 1)
  ebola.pr[i,2] <- length(e[[i]]$tip.label)
}

#Calculating Z-Scores
for(i in 1:length(ebola.pr[,3])){
  ebola.pr[i,3] <- ebola.pr[i,1]*93-ebola.pr[i,2]
}
ebola.pr[,3] <- scale(ebola.pr[,3])
```

Visualizing the tree with node probabilities
```{r}
ebola2 <- ebola
ebola2$node.label <- round(ebola.pr[,1], digits=2)
plot(ebola2, show.node.label = TRUE, cex=.7, show.tip.label=FALSE)

#plotting the full ebola tree colored by node probabilities
pr.palatte <- colorRampPalette(colors= c("#8bb9b9", "#284e57"))(92)
pr.tree <- rep(0, 92*2)
pr.cols <- order(ebola.pr[,1]) + 93
for(i in 1:length(pr.cols)){
  indicies <- which(ebola$edge[,1]==pr.cols[i])
  pr.tree[indicies[1]] <- pr.palatte[i]
  pr.tree[indicies[2]] <- pr.palatte[i]
}
plot(ebola2, show.tip.label=FALSE, edge.color=pr.tree, edge.width=3, show.node.label=TRUE, cex=0.5)
```

Visualizing outliers by Z-scores in the full tree
```{r}
#Visualizing z scors and outliers with histogram in ggplot
zs <- as.data.frame(ebola.pr)
zs$outlier <- ifelse(abs(zs[,3]>2),TRUE, FALSE)
cols <- c("#a6a2a8","#284e57")
ggplot(data=zs, aes(zs$ZScore, fill=zs$outlier)) + 
  geom_histogram(binwidth=.1) + 
  xlab("Z-Scores of Branch Length Expectations") +
  ylab("Frequency") +
  theme(legend.position="none") + 
  scale_fill_manual(values= cols) + 
  geom_segment(x=2, y= 0, yend=20, xend=2, linetype=2)+
  theme(legend.position="none", axis.text=element_text(size=16), axis.title = element_text(size=20))
```

Visualizing Outliers on the tree
```{r}
#With tip labels
t.col <- ifelse(ebola$edge[,1] <= 105 & ebola$edge[,1] >= 97, "#284e57", "#a6a2a8")
wid <-ifelse(ebola$edge[,1] <= 105 & ebola$edge[,1] >= 97, 3, 1)
plot(ebola2, show.node.label = TRUE, cex=.7, align.tip.label=TRUE, edge.color=t.col, edge.width=wid)

#Without tip labels
t.col2 <-ifelse(e[[4]]$edge[,1] <= 66 & e[[4]]$edge[,1] >= 58, "#284e57", "#a6a2a8")
wid2 <-ifelse(e[[4]]$edge[,1] <= 66 & e[[4]]$edge[,1] >= 58, 3, 1)
subt <- extract.clade(ebola2, 97)
plot(subt, cex=1, show.tip.label=FALSE, edge.color=t.col2, edge.width=wid2+3, show.node.label=TRUE)
```

Node probabilities plotted against tips within the clades
```{r}
zs$i <- as.factor(dist.nodes(ebola)[1,94:185])
#colrs <- colorRampPalette(brewer.pal(11,"PiYG"))(92)
colrs <- colorRampPalette(colors =c("#284e57", "mediumvioletred"))(92)

#Scatterplot of estimated versus actual node proportions
ggplot(data=zs, (aes(x=Node.Pr, y=N.Tips/93))) + 
  geom_point(aes(size=abs(ZScore), alpha=.8, color=i)) + 
  xlab(expression(paste("Estimated Node Proportion (", pi, ")"))) +
  ylab(paste("Actual Node Proportion (p)")) +
  geom_segment(x=0.0, y=0, xend=1.2, yend=1.2, linetype=1, color="#a6a2a8") +
  theme(legend.position="none", axis.text=element_text(size=16), axis.title = element_text(size=20)) +
  scale_color_manual(values=colrs)
```

Coloring the full ebola tree by the clades in the scatterplot above
```{r}
x <-zs$i
colmap <- as.data.frame(cbind(x, 1:92))
treecol <- rep(0, 92)
for(i in 1:92){
  treecol[i] <- colrs[colmap[i,1]]
}
treecol <- rep(treecol, each=2)
plot(ebola2, show.tip.label=FALSE, edge.color=treecol, edge.width=5)
```

Tree with outlier at tip 38
```{r}
#Looking at the tree without tip 38, long branch outluer
dt.ebola <- drop.tip(ebola, 38)
dt.e <- subtrees(dt.ebola)
dt.ebola.pr <- matrix(NA, nrow=length(dt.e), ncol = 3)
colnames(dt.ebola.pr) <- c("Node.Pr", "N.Tips", "ZScore")

for(i in 1:length(dt.e)){
  dt.ebola.pr[i,1] <- nu.node.prob(dt.ebola, dt.e[[i]], 1)
  dt.ebola.pr[i,2] <- length(dt.e[[i]]$tip.label)
}

#Calculating Z-Scores
for(i in 1:length(dt.ebola.pr[,3])){
  dt.ebola.pr[i,3] <- dt.ebola.pr[i,1]*92- dt.ebola.pr[i,2]
}
dt.ebola.pr[,3] <- scale(dt.ebola.pr[,3])

#Visualizing the tree without tip 38
dt.ebola2 <- dt.ebola
dt.ebola2$node.label <- round(dt.ebola.pr[,1], digits=5)
plot(dt.ebola2, show.node.label = TRUE, cex=.7, align.tip.label=TRUE)


#Visualizing new outliers with ggplot (They're pretty much the same but a little closer together)
zs.2 <- as.data.frame(dt.ebola.pr)
zs.2$outlier <- ifelse(abs(zs.2[,3]>2),TRUE, FALSE)
cols <- c("#a6a2a8","#284e57")
ggplot(data=zs.2, aes(zs.2$ZScore, fill=zs.2$outlier)) + 
  geom_histogram(binwidth=.1) + 
  xlab("Z-Scores of Branch Length Expectations(Tip 38 Dropped)") + 
  ylab("Frequency") + 
  theme(legend.position="none") + 
  scale_fill_manual(values= cols) + 
  geom_segment(x=2-.05, y= 0, yend=20, xend=2-.05, linetype=2)


#comparing the probabilities with and without the outlying tip 38
x1 <- c(zs$Node.Pr[1:11], zs$Node.Pr[13:92])
x2 <- zs.2$Node.Pr[1:91]
diff <- as.data.frame(x2-x1)
l.bound <-as.numeric(apply(diff, 2, mean) - 2*apply(diff, 2, sd))
u.bound <-as.numeric(apply(diff, 2, mean) + 2*apply(diff, 2, sd))
ggplot(diff, aes(diff)) + 
  geom_histogram() +
  xlab("Differences between node probabilities when tip 38 is dropped") +
  geom_segment(x= u.bound, y= 0,yend=50, xend=u.bound, linetype=2) +
  geom_segment(x= l.bound, y= 0,yend=50, xend=l.bound, linetype=2)
```
